//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUSUMediaSite.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCommon
    {
        public tbCommon()
        {
            this.tbEqInfo = new HashSet<tbEqInfo>();
            this.tbMediaInfo = new HashSet<tbMediaInfo>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Tag { get; set; }
    
        public virtual ICollection<tbEqInfo> tbEqInfo { get; set; }
        public virtual ICollection<tbMediaInfo> tbMediaInfo { get; set; }
    }
}
